# Generated by Django 4.1.7 on 2023-03-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={"ordering": ("-date_created",)},
        ),
    ]
